name: Prod Server Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: wgd-dev

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Build
      run: docker build -t wikigdrive-prod --build-arg "GIT_SHA=${GITHUB_SHA}" .

    - name: Build
      run: docker build -t "transform-watch:prod" --build-arg "GIT_SHA=${GITHUB_SHA}" apps/transform-watch

    - name: Build
      run: docker build -t "hugo-render:prod" --build-arg "GIT_SHA=${GITHUB_SHA}" apps/hugo-render

    - name: Stop
      run: docker stop wikigdrive-prod
      continue-on-error: true

    - name: Remove
      run: docker rm wikigdrive-prod
      continue-on-error: true

    - name: Start
      run: |
        docker run -d --name wikigdrive-prod \
          -v wikiGDriveProd:/data \
          -v /home/githubactions/wikigdrive/service_account.json:/service_account.json \
          --publish 127.0.0.1:3000:3000 \
          --restart unless-stopped \
          wikigdrive-prod wikigdrive-ts \
          --service_account /service_account.json \
          --share_email mie-docs-wikigdrive@wikigdrive.iam.gserviceaccount.com \
          --workdir /data \
          server 3000

    - name: Stop and remove
      run: docker stop transform-preview-prod ; docker rm transform-preview-prod
      continue-on-error: true

    - name: Start
      run: |
        docker run -d --name transform-preview-prod \
          --restart unless-stopped \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v wikiGDriveProd:/data \
          -v /var/www/preview-prod:/preview \
          -e VOLUME_DATA=/var/lib/docker/volumes/wikiGDriveProd/_data \
          -e VOLUME_PREVIEW=/var/www/preview-prod \
          -e RENDER_IMAGE=hugo-render:prod \
          -e DOMAIN=https://wikigdrive.com \
          transform-watch:prod
